/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/NewPool.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useTexture } from "@react-three/drei";
import { useCustomization } from "./Context/Customization";

const NewPool = (props) => {
  const { nodes, materials } = useGLTF("/models/NewPool.gltf");
  const { poolSize, poolColor, groundColor, stairType } = useCustomization();
  return (
    <group {...props} dispose={null}>

      //pool 3x6
      <group name="pool3x6" visible={poolSize === 1}>
        <group position={[-1.51, 0.8, -1.84]}>
          <mesh
            geometry={nodes.Cube018.geometry}
            material={materials.spotlight}
          />
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials["Stainless steel"]}
          />
        </group>
        <mesh
          geometry={nodes.pool_edge_tile__3x6.geometry}
          material={materials["pool edge tiles"]}
        />
        <mesh
          geometry={nodes.pool_body_3x6.geometry}
          material={materials["pool tiles"]}
        />
        <mesh
          geometry={nodes.pool_stairs_wide_3x6.geometry}
          material={materials["pool tiles"]}
          position={[0, 0, -1.5]}
        />
        <mesh
          geometry={nodes.pool_stairs_corner_3x6.geometry}
          material={materials["pool tiles"]}
          position={[0.9, 0.53, -2.4]}
          rotation={[0, -Math.PI / 4, 0]}
        />
      </group>

      //pool 5x8
      <group name="pool5x8" visible={poolSize === 2}>
        <group position={[-2.02, 0.8, -2.45]} scale={[1.33, 1, 1.33]}>
          <mesh
            geometry={nodes.Cube023.geometry}
            material={materials["spotlight.002"]}
          />
          <mesh
            geometry={nodes.Cube023_1.geometry}
            material={materials["Stainless steel.002"]}
          />
        </group>
        <mesh
          geometry={nodes.pool_edge_tile__5x8.geometry}
          material={materials["pool edge tiles.002"]}
          scale={[1.33, 1, 1.33]}
        />
        <mesh
          geometry={nodes.pool_body_5x8.geometry}
          material={materials["pool tiles.002"]}
          scale={[1.33, 1, 1.33]}
        />
        <mesh
          geometry={nodes.pool_stairs_wide_5x8.geometry}
          material={materials["pool tiles.002"]}
          position={[0, 0, -2]}
          scale={[1.33, 1, 1.33]}
        />
        <mesh
          geometry={nodes.pool_stairs_corner_5x8.geometry}
          material={materials["pool tiles.002"]}
          position={[1.21, 0.53, -3.2]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={[1.33, 1, 1.33]}
        />
      </group>

    </group>
  );
};

export default NewPool;

useGLTF.preload("/models/NewPool.gltf");
