/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/PahlenPool.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PahlenPool = (props) => {
  const { nodes, materials } = useGLTF('/models/PahlenPool.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.46, 0.8, -1.84]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.spotlight} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Stainless steel']} />
      </group>
      <mesh geometry={nodes.pool_edge_tile_4X6.geometry} material={materials['pool edge tiles']} />
      <mesh geometry={nodes.pool_body_4X6.geometry} material={materials['pool tiles']} />
      <mesh geometry={nodes.pool_big_stairs_4x6.geometry} material={materials['pool tiles']} position={[0, -0.48, -1.34]} />
      <mesh geometry={nodes.pool_corner_stairs_4x6.geometry} material={materials['pool tiles']} position={[-0.42, -0.48, -1.76]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.pool_big_stairs_5x8.geometry} material={materials['pool tiles']} position={[0, -0.48, -1.79]} scale={[1.33, 1, 1.33]} />
      <mesh geometry={nodes.pool_body_5x8.geometry} material={materials['pool tiles']} scale={[1.33, 1, 1.33]} />
      <mesh geometry={nodes.pool_corner_stairs_5x8.geometry} material={materials['pool tiles']} position={[-0.56, -0.48, -2.35]} rotation={[0, Math.PI / 4, 0]} scale={[1.33, 1, 1.33]} />
      <mesh geometry={nodes.pool_edge_tile_5x8.geometry} material={materials['pool edge tiles']} scale={[1.33, 1, 1.33]} />
      <group position={[-1.95, 0.8, -2.46]} scale={[1.33, 1, 1.33]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.spotlight} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Stainless steel']} />
      </group>
    </group>
  )
}

export default PahlenPool

useGLTF.preload('/models/PahlenPool.gltf')
