/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Skrivbord.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from './Context/Customization';
import { useTexture } from '@react-three/drei';
import * as THREE from 'three';


const Skrivbord = (props) => {
  const { nodes, materials } = useGLTF('/models/Skrivbord.gltf')
  const { ben, färg, rygg, låda, färgBen, tillbehör } = useCustomization();



  const vit = {
    color: 0xffffff,
    side: 2,
    roughness: 1,
  }

  const svart = {
    color: 0x000000,
    side: 2,
    roughness: 1,
  }

  const Wood = useTexture({
    map: '/textures/Wood/Wood_025_basecolor.jpg',
    normalMap: '/textures/Wood/Wood_025_normal.jpg',
    roughnessMap: '/textures/Wood/Wood_025_roughness.jpg',
    aoMap: '/textures/Wood/Wood_025_ambientOcclusion.jpg',
  })

  Wood.map.repeat.set(8, 8)
  Wood.map.wrapS = Wood.map.wrapT = THREE.RepeatWrapping
  Wood.normalMap.repeat.set(8, 8)
  Wood.normalMap.wrapS = Wood.normalMap.wrapT = THREE.RepeatWrapping
  Wood.roughnessMap.repeat.set(8, 8)
  Wood.roughnessMap.wrapS = Wood.roughnessMap.wrapT = THREE.RepeatWrapping
  Wood.aoMap.repeat.set(8, 8)
  Wood.aoMap.wrapS = Wood.aoMap.wrapT = THREE.RepeatWrapping
  Wood.side = THREE.DoubleSide


  return (
    <group {...props} dispose={null}>

      <group position={[0, 0.76, 0]} rotation={[0, 0.1, 0]} visible={tillbehör===2}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.MB_keyboard} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials.MB_metal} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['MB_metal 2']} />
        <mesh geometry={nodes.Plane002_4.geometry} material={materials['MB_gray logo']} />
        <mesh geometry={nodes.Plane002_5.geometry} material={materials.MB_desktop} />
        <mesh geometry={nodes.Plane002_6.geometry} material={materials['MB_screen black']} />
        <mesh geometry={nodes.Plane002_7.geometry} material={materials['MB_plastic 01']} />
        <mesh geometry={nodes.Plane002_8.geometry} material={materials['MB_plastic 02']} />
        <mesh geometry={nodes.Plane002_9.geometry} material={materials.MB_blue} />
        <mesh geometry={nodes.Plane002_10.geometry} material={materials['MB_metal 4']} />
        <mesh geometry={nodes.Plane002_11.geometry} material={materials['MB_metal black']} />
      </group>
      

      <group position={[0.45, 0.76, -0.1]} visible={tillbehör===2}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[0, 0.07, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[0.02, 0.08, -0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.002']} position={[0.03, 0.08, 0.01]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.002']} position={[0.01, 0.08, 0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane005.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane006.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.002']} position={[0, 0.12, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.002']} position={[0, 0.08, 0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane012.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.002']} position={[-0.04, 0.07, -0.02]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane014.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane015.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane016.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane017.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane018.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane019.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane020.geometry} material={materials['Material.002']} position={[0, 0.09, 0.01]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane021.geometry} material={materials['Material.002']} position={[0, 0.11, 0.01]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane022.geometry} material={materials['Material.002']} position={[-0.03, 0.11, -0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane023.geometry} material={materials['Material.002']} position={[0, 0.12, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane024.geometry} material={materials['Material.002']} position={[0, 0.08, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane025.geometry} material={materials['Material.002']} position={[-0.03, 0.08, -0.01]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane026.geometry} material={materials['Material.001']} position={[0, 0.12, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane027.geometry} material={materials['Material.002']} position={[-0.02, 0.08, -0.01]} rotation={[0, 1.57, 0]} />
      </group>


      <group>
        <mesh geometry={nodes.Bänk.geometry}>
        <meshStandardMaterial {...färg === "vit" ? vit : svart} />
        </mesh>
        <mesh geometry={nodes.Back.geometry} visible = {rygg === 1}>
        <meshStandardMaterial {...färg === "vit" ? vit : svart} />
        </mesh>
        <mesh geometry={nodes.Ben_Klassisk.geometry} material={materials.DeskBody} visible={ben===1}>
        <meshStandardMaterial {...färgBen === "vit" ? vit : svart} />
        </mesh>
        <mesh geometry={nodes.Ben_Design.geometry} material={materials.DeskBody} visible={ben===2}>
        <meshStandardMaterial {...färgBen === "vit" ? vit : svart} />
        </mesh>
      </group>
     


      <group position={[-0.53, 0.76, -0.16]} rotation={[0, 0.56, 0]} visible={tillbehör===2}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['black plastic.001']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['silver plastic']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['silver metal']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.emision} />
      </group>

      
      <group position={[0.7, 0, 0.77]} rotation={[0, -1.07, 0]} visible={tillbehör===2}>
        <mesh geometry={nodes.Cube001.geometry} material={materials[' Cadeira escritorio Metal']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Cadeira escritorio Plastic.Rough_Light']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials[' Cadeira escritorio Metal']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials[' Cadeira escritorio Metal']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials[' Cadeira escritorio Metal_Black']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials[' Cadeira escritorio Metal_Black']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials[' Cadeira escritorio Material']} />
      </group>
      
    
    
      <group visible={låda===1}>
        <mesh geometry={nodes.Desk003.geometry} material={materials.DeskBody}>
        <meshStandardMaterial {...färgBen === "vit" ? vit : svart} />
        </mesh>
        <mesh geometry={nodes.Desk003_1.geometry} material={materials.Handle} />
      </group>

      
      <group visible={låda===2}>
        <mesh geometry={nodes.Desk007.geometry} material={materials.DeskBody}>
        <meshStandardMaterial {...färgBen === "vit" ? vit : svart} />
        </mesh>
        <mesh geometry={nodes.Desk007_1.geometry} material={materials.Handle} />
      </group>
    </group>
  )
}

export default Skrivbord

useGLTF.preload('/models/Skrivbord.gltf')
